server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity_service
              uri: ${app.services.identity.url}
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=2
                - AddRequestHeader=X-Gateway-Token, ${app.gateway-token}
            - id: profile_service
              uri: ${app.services.profile.url}
              predicates:
                - Path=${app.api-prefix}/profile/**
              filters:
                - StripPrefix=2
            - id: notification_service
              uri: ${app.services.notification.url}
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                - StripPrefix=2
            - id: post_service
              uri: ${app.services.post.url}
              predicates:
                - Path=${app.api-prefix}/post/**
              filters:
                - StripPrefix=2
            - id: file_service
              uri: ${app.services.file.url}
              predicates:
                - Path=${app.api-prefix}/file/**
              filters:
                - StripPrefix=2
            - id: chat_service
              uri: ${app.services.chat.url}
              predicates:
                - Path=${app.api-prefix}/chat/**
              filters:
                - StripPrefix=2
            - id: search_service
              uri: ${app.services.search.url}
              predicates:
                - Path=${app.api-prefix}/search/**
              filters:
                - StripPrefix=2
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.zaxxer.hikari: off
    org.hibernate.engine.jdbc.connections.internal: off
    org.hibernate.orm.connections.pooling: WARN

web:
  url: ${WEB_URL}

app:
  api-prefix: ${API_GATEWAY_PREFIX}
  gateway-token: ${API_GATEWAY_TOKEN}
  services:
    identity:
      url: ${IDENTITY_SERVICE_HOST}
    profile:
      url: ${PROFILE_SERVICE_HOST}
    notification:
      url: ${NOTIFICATION_SERVICE_HOST}
    post:
      url: ${POST_SERVICE_HOST}
    file:
      url: ${FILE_SERVICE_HOST}
    chat:
      url: ${CHAT_SERVICE_HOST}
    search:
      url: ${SEARCH_SERVICE_HOST}
